CREATE TABLE users (
    US_ID INT AUTO_INCREMENT PRIMARY KEY,
    US_lastname VARCHAR(100) NOT NULL,
    US_firstname VARCHAR(150) NOT NULL,
    US_role VARCHAR(150) NOT NULL,
    US_password VARCHAR(255) NOT NULL,
    US_phone VARCHAR(10) NOT NULL,
    US_email VARCHAR(150) NOT NULL UNIQUE
);