CREATE TABLE users (
    US_ID INT AUTO_INCREMENT PRIMARY KEY,
    US_lastname VARCHAR(100) NOT NULL,
    US_firstname VARCHAR(150) NOT NULL,
    US_role VARCHAR(150) NOT NULL,
    US_password VARCHAR(255) NOT NULL,
    US_phone VARCHAR(10) NOT NULL,
    US_email VARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE recipes (
    RE_ID INT AUTO_INCREMENT PRIMARY KEY,
    RE_name VARCHAR(100) NOT NULL,
    RE_preparation_time INTEGER NOT NULL,
    RE_cooking_time INTEGER NOT NULL,
    RE_cal INTEGER NOT NULL,
    RE_visibility BIT DEFAULT FALSE
)

CREATE TABLE products (
    PR_ID INT AUTO_INCREMENT PRIMARY KEY,
    PR_lib VARCHAR(100) NOT NULL,
    PR_type VARCHAR(100) NOT NULL,
    PR_cal INTEGER NOT NULL
)